config/routes.rb
Secure1::Application.routes.draw do

  resources :gs_users
  resources :items
  root 'gs_users#index'
  get 'login' => 'login#login'
  post 'submit_login'=> 'login#submit_login'
  get 'fail' => 'login#fail'
  get 'success' => 'login#success'

end

app/models/connection_factory.rb
class ConnectionFactory

  def self.get_connection
    return ActiveRecord::Base.connection
  end

  def get_connection
    self.class.get_connection
  end

  def self.initialize_test_data
    GsUser.all.each { |user| user.destroy }
    Item.all.each { |item| item.destroy }
    [%w(Jerry comic seller), %w(Cosmo kramer seller),
     %w(Elaine witchy buyer), %w(George bosco buyer)].each do |name, pw, type|
      GsUser.create(:user_name => name, :password => pw, :user_type => type)
    end
    [['Jerry', 'Puffy Shirt - Look like a <b>pirate<\b>', 18.00],
     ['Jerry', 'Stinky car', 18000.00],
     ['Cosmo', 'Coffee table book', 16.00],
     ['Cosmo', 'Calvin Klein Underwear', 8.00]].each do |name, description, price|
      Item.create(:user_id => GsUser.find_by_name(name).id, :description => description,
                  :price => price)
    end
  end
end

app/models/gs_user.rb
class GsUser < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged

  validates_uniqueness_of :user_name, :allow_blank => false
  validates_presence_of :password
  has_many :items, :foreign_key => 'user_id', :order => 'description asc'

  before_create :assign_slug

  def assign_slug
    self.slug = UUID.generate
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug, use: :slugged

  before_save :sanitize_description
  before_create :assign_slug

  def sanitize_description
    self.description = Sanitize.clean(self.description, Sanitize::Config::BASIC)
  end

  def assign_slug
    self.slug = UUID.generate
  end

end

app/models/login_data.rb
class LoginData
  include ActiveModel::Validations
  validates_with LoginDataValidator

  attr_accessor :user_name, :password

  def initialize(attributes = {})
    self.user_name = attributes[:user_name]
    self.password = attributes[:password]
  end

end

app/models/login_data_validator.rb
class LoginDataValidator < ActiveModel::Validator
  def validate(record)
    unless record.user_name.match(/\w{4,30}/)
      record.errors[:user_name] = ('invalid user name')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #skip_before_filter :verify_authenticity_token
end

app/controllers/gs_users_controller.rb
class GsUsersController < ApplicationController

  def index

  end

end

app/controllers/items_controller.rb
class ItemsController  < ApplicationController

  before_filter :find_item, only: [:edit, :update, :show]
  before_filter :verify_owner, only: [:edit, :update]

  #display items for logged in user only
  def index
    redirect_to login_path unless session[:user_id].present?
    @user = GsUser.find(session[:user_id])
    @items = @user.items
  end

  def edit

  end

  def update
    if @item.update_attributes(params.require(:item).permit(:description, :price))
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def show

  end

  private

  def find_item
    @item = Item.friendly.find(params[:id])
  end

  def verify_owner
    redirect_to items_path unless @item.user_id == session[:user_id]
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def login

  end

  def fail

  end

  def success

  end

  def submit_login
    #real code
    user = GsUser.where(:user_name => params[:login][:user_name], :password => params[:login][:password]).first
    #direct sql code
    #here we can get into the success branch, or execute arbitrahttp://slashdot.org/ry sql, e.g. by using user_name = "' ; my sql code here -- '"
    #login_data = LoginData.new(params[:login])
    #valid = login_data.valid?
    # user = ActiveRecord::Base.connection.send(:select, ("SELECT * from gs_users where user_name='#{params[:login][:user_name]}' AND password = '#{params[:login][:password]}'")).rows.present?
    if user
      session[:user_id] = user.id
      redirect_to items_path
    else
      render 'fail'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gs_users/index.html.haml
%h1 Hello from Garage Sale

app/views/items/edit.html.haml
%div= link_to 'Index', items_path
%div
  = simple_form_for @item do |f|
    = f.input :description
    = f.input :price
    = f.submit

app/views/items/index.html.haml
%ul
  - @items.each do |item|
    %li
      = link_to(truncate(item.description), item_path(item))
      |
      = link_to('Edit', edit_item_path(item))

app/views/items/show.html.haml
= link_to 'Edit', edit_item_path(@item)
|
= link_to 'Index', items_path
%div
  %p
    Description:
    = sanitize(@item.description)
  %p Price: #{@item.price}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Garage Sale
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/login/fail.html.haml
%h1 Fail

app/views/login/login.html.haml
%h1 Login
= simple_form_for :login, :url => submit_login_path, :method => :post do |f|
  = f.input :user_name, :value => nil, :as => :string
  = f.input :password, :value => nil, :as => :password
  = f.submit 'Login'

app/views/login/success.html.haml
%h1 Success